version: "3.9"
services:
  react_next_pizza:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./react_next_pizza
    ports:
      - "3010:3000"
  react_web_portfolio:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./react_web_portfolio
    ports:
      - "3014:80"
  musician_info_site:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./musician_info_site
    ports:
      - "3015:80"
  softline_info_site:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./softline_info_site
    ports:
      - "3016:80"
  database_nzkt:
    build:
     context: ./nzkt
     dockerfile: DockerfileJsonServer
    ports:
     - "4001:4000"
  nzkt:
    build:
     context: ./nzkt
     dockerfile: Dockerfile
    ports:
     - "3017:80"
  green_api_chat:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./green-api-chat
    ports:
      - "3018:92"