version: "3.9"
services:
#  react_next_pizza:
#    build:
#      dockerfile: Dockerfile
#      context: ./react_next_pizza
#    ports:
#      - "3010:80"
  js-calendar:
    build:
      dockerfile: Dockerfile
      context: ./js-calendar
    ports:
      - "3011:80"
  js-stickers:
    build:
      dockerfile: Dockerfile
      context: ./js-stickers
    ports:
      - "3012:80"
  js-todolist:
    build:
      dockerfile: Dockerfile
      context: ./js-todolist
    ports:
      - "3013:80"
  react_web_portfolio:
    build:
      dockerfile: Dockerfile
      context: ./react_web_portfolio
    ports:
      - "3014:80"